export const allGames = [
  "Monster Hunter",
  "Monster Hunter G",
  "Monster Hunter Portable",
  "Monster Hunter 2",
  "Monster Hunter G",
  "Monster Hunter Portable 2nd",
  "Monster Hunter 3",
  "Monster Hunter Portable 3rd",
  "Monster Hunter 3 G",
  "Monster Hunter 4",
  "Monster Hunter 4 G",
  "Monster Hunter X",
  "Monster Hunter XX",
  "Monster Hunter World",
  "Monster Hunter World:Iceborne",
  "Monster Hunter Rise",
  "Monster Hunter Rise:Sunbreak",
  "Monster Hunter Frontier",
  "Monster Hunter Frontier G",
  "Monster Hunter Frontier Z",
  "Monster Hunter Spirits",
  "Monster Hunter Stories",
  "Monster Hunter Explore",
]
